val bold : string -> string
val underline : string -> string
val invert : string -> string
val red : string -> string
val green : string -> string
val yellow : string -> string
val blue : string -> string
val magenta : string -> string
val cyan : string -> string
val gray : string -> string
val white : string -> string
val light_gray : string -> string
val light_red : string -> string
val light_green : string -> string
val light_yellow : string -> string
val light_blue : string -> string
val light_magenta : string -> string
val light_cyan : string -> string
val bg_red : string -> string
val bg_green : string -> string
val bg_yellow : string -> string
val bg_blue : string -> string
val bg_magenta : string -> string
val bg_cyan : string -> string
val bg_gray : string -> string
val bg_white : string -> string
val bg_light_gray : string -> string
val bg_light_red : string -> string
val bg_light_green : string -> string
val bg_light_yellow : string -> string
val bg_light_blue : string -> string
val bg_light_magenta : string -> string
val bg_light_cyan : string -> string
